name: Deploy to Netlify
on:
  push:
    branches:
      - main
jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - moonbeaming
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Verify Nix installation
        run: nix --version
      - name: Build Website
        run: nix develop .#${{ matrix.package }} --command just ${{ matrix.package }}-build
      - name: Capitalize package name
        id: capitalize_package
        run: echo "CAPITALIZED_PACKAGE_NAME=$(echo ${{ matrix.package }} | tr '[:lower:]' '[:upper:]')" >> $GITHUB_OUTPUT
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: ./packages/${{ matrix.package }}/dist
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: Deploy from GitHub Actions
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets[format('NETLIFY_SITE_ID_{0}', steps.capitalize_package.outputs.CAPITALIZED_PACKAGE_NAME)] }}
        timeout-minutes: 1
